### ISSUE TITLE
Broader compatibility would be nice

### ISSUE THREAD

**Issue by netllama** [meesaltena/SSHHeatmap#5]
/var/log/auth.log is an Ubuntu (only) thing.  But that's a minor issue, as people can still grep the log with these failures to generate the expected input.

However, the bigger problem is the assumption that people are running sshd with password auth enabled.  That's a huge security risk, and is strongly discouraged for internet facing servers.  They should have locked down their sshd configuration to only permit keys.  Once that happens, this tool becomes useless.  I see literally hundreds of ssh attempts every day, but none of them fail due to an invalid password, because I don't permit password auth. Nearly all of them are rejected due to not having a valid key.  This tool should support that use case.

**Comment by meesaltena** [comment]
You can use
```bash
grep "authentication failure\| Failed password" /var/log/auth.log > failed_attempts.txt
```
to also include failed login attempts with ssh keys. I updated the README to reflect this in https://github.com/meesaltena/SSHHeatmap/commit/a5b56d5968b3f7a03d059f00dc27fb0243fcb02d. Thanks for your suggestion.
